# Generated by Django 5.1.6 on 2025-02-24 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Téléphone'), ('address', 'Adresse'), ('social', 'Réseaux sociaux')], help_text='Type de contact', max_length=20)),
                ('value', models.CharField(help_text='Valeur du contact (adresse email, numéro, etc.)', max_length=200)),
                ('label', models.CharField(blank=True, help_text='Label ou titre du contact', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Fichier image', upload_to='content_images/')),
                ('alt_text', models.CharField(blank=True, help_text="Texte alternatif pour l'accessibilité", max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage de l'image")),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du service', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description du service')),
                ('price', models.DecimalField(decimal_places=2, help_text='Tarif du service', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du contenu', max_length=200)),
                ('slug', models.SlugField(help_text='Identifiant URL unique', unique=True)),
                ('description', models.TextField(blank=True, help_text='Description ou résumé')),
                ('content', models.TextField(blank=True, help_text='Contenu complet (texte, HTML, etc.)')),
                ('visible_in_portfolio', models.BooleanField(default=True, help_text='Afficher dans la page Portfolio')),
                ('visible_in_realisations', models.BooleanField(default=True, help_text='Afficher dans la page Réalisations')),
                ('featured_in_homepage', models.BooleanField(default=False, help_text="Mettre en avant dans le carrousel de la page d'accueil")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('featured_image', models.ForeignKey(blank=True, help_text='Image mise en avant (si différente de la première image)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_in', to='content.contentimage')),
            ],
        ),
        migrations.AddField(
            model_name='contentimage',
            name='content_item',
            field=models.ForeignKey(help_text='Contenu auquel cette image appartient', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='content.contentitem'),
        ),
    ]
