# Generated by Django 5.1.6 on 2025-02-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterModelOptions(
            name='contentimage',
            options={'ordering': ['ordre']},
        ),
        migrations.RenameField(
            model_name='contentimage',
            old_name='content_item',
            new_name='contenu_lié',
        ),
        migrations.RenameField(
            model_name='contentimage',
            old_name='order',
            new_name='ordre',
        ),
        migrations.RenameField(
            model_name='contentitem',
            old_name='featured_in_homepage',
            new_name='afficher_dans_homepage',
        ),
        migrations.RenameField(
            model_name='contentitem',
            old_name='content',
            new_name='contenu',
        ),
        migrations.RenameField(
            model_name='contentitem',
            old_name='featured_image',
            new_name='image_mise_en_avant',
        ),
        migrations.RenameField(
            model_name='contentitem',
            old_name='title',
            new_name='titre',
        ),
        migrations.RenameField(
            model_name='contentitem',
            old_name='visible_in_portfolio',
            new_name='visible_dans_le_portfolio',
        ),
        migrations.RenameField(
            model_name='contentitem',
            old_name='visible_in_realisations',
            new_name='visible_dans_les_realisations',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='price',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='contentitem',
            name='description',
        ),
        migrations.AddField(
            model_name='contentitem',
            name='mot_clé',
            field=models.TextField(blank=True, help_text='Description ou résumé sous forme de mots clés'),
        ),
    ]
