# Generated by Django 5.1.6 on 2025-02-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#FFFFFF', help_text='Couleur de fond (ex: #FFFFFF)', max_length=7)),
                ('content_color', models.CharField(default='#F0F0F0', help_text='Couleur du contenu (ex: #F0F0F0)', max_length=7)),
                ('accent_color', models.CharField(default='#007BFF', help_text="Couleur d'accord (ex: #007BFF)", max_length=7)),
                ('contrast_color', models.CharField(default='#000000', help_text='Couleur de contraste (ex: #000000)', max_length=7)),
            ],
            options={
                'verbose_name': 'Paramètre du thème',
                'verbose_name_plural': 'Paramètres du thème',
            },
        ),
    ]
